name: hybrid_clock
description: Hybrid clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  flare_flutter: ^1.8.3
  # auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  async: ^2.3.0
  # google_fonts: ^0.3.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Regular.ttf
  assets:
    - assets/animations/
    - assets/fonts/
